### ISSUE TITLE
A link to pipenv installation guide page is broken

### ISSUE THREAD

**Issue by yon666632** [aws-solutions/connected-mobility-solution-on-aws#10]
**Describe the bug**

On [pipenv installan part](https://github.com/aws-solutions/connected-mobility-solution-on-aws#pipenv) , there is a link for pipenv official page. But if you click the link, it tells you 404. The URL is not current.
current link is : https://pipenv.pypa.io/en/latest/installation/
But, the link should be : https://pipenv.pypa.io/en/latest/installation.html
So, this part needs to be updated.

**To Reproduce**

Click the link. Then you will see 404.  
Page you will see is attached below

**Expected behavior**

Should jump to a correct page.
Which is https://pipenv.pypa.io/en/latest/installation.html

**Please complete the following information about the solution:**
- [x] Version: [v1.0.0]
- [x] Region: [Any region since this is a guide page]
- [ ] Was the solution modified from the version published on this repository?
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs?

**Screenshots**

<img width="1001" alt="スクリーンショット 2023-11-24 10 44 30" src="https://github.com/aws-solutions/connected-mobility-solution-on-aws/assets/1127620/b6fe6174-a32a-4111-937a-8a797f897a0a">

**Additional context**

**Comment by amohames** [comment]
Acknowledged! We will work to review and resolve this issue. Thanks.

**Comment by amohames** [comment]
Fix applied
