### ISSUE TITLE
Blank page on "CMS Vehicle Simulator on AWS" Cloudfront URL after setting up the implementation guide

### ISSUE THREAD

**Issue by XsarfrazX** [aws-solutions/connected-mobility-solution-on-aws#21]
**What is your question?**
After following the guide to deploy ACDP and installing the CMS Vehicle Simulator on AWS - which shows successful deployment [1] in the portal. Upon clicking the link to service and accessing the cloudfront url for vehicle simulator, a blank page appears [2].

 Are there any additional steps to properly install and view the frontend for this module?

[1] 
![cms_error_1](https://github.com/aws-solutions/connected-mobility-solution-on-aws/assets/36766048/eb287917-e0e9-494a-ab7f-71f8fca0531b)

[2] 
![cms_error_2](https://github.com/aws-solutions/connected-mobility-solution-on-aws/assets/36766048/8aa5afbf-74f7-4114-a81b-9644b1206631)

**Comment by mttwise** [comment]
Hi @XsarfrazX, thanks for reporting the issue.

We have recently been made aware of this issue for anyone not based in the United States.  
I first want to verify if you are in the US or not.  If you are in the US, we can look further into what could be causing this error.

If you are not in the US, please go to the CloudFront distribution and update the geographical restrictions to include the country you are trying to access from.

![image](https://github.com/aws-solutions/connected-mobility-solution-on-aws/assets/24458226/56c6ce90-af45-4ca4-92df-c93035e6b825)

If this does not resolve your issue, please let me know which AWS region you are deploying to so we can try to replicate it on our side.

Thanks,
Matt

**Comment by XsarfrazX** [comment]
> Hi @XsarfrazX, thanks for reporting the issue.
> 
> We have recently been made aware of this issue for anyone not based in the United States. I first want to verify if you are in the US or not. If you are in the US, we can look further into what could be causing this error.
> 
> If you are not in the US, please go to the CloudFront distribution and update the geographical restrictions to include the country you are trying to access from.
> 
> ![image](https://private-user-images.githubusercontent.com/24458226/302330701-56c6ce90-af45-4ca4-92df-c93035e6b825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDY4ODMsIm5iZiI6MTcwNzE0NjU4MywicGF0aCI6Ii8yNDQ1ODIyNi8zMDIzMzA3MDEtNTZjNmNlOTAtYWY0NS00Y2E0LTkyZGYtYzkzMDM1ZTZiODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDE1MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZmIyZjI5M2I0ZGU0NWMyNTk5YjkxOWI5Y2FhNzNlYmY0YjIwNGNjNTIzZDJhZjg4NjVjN2IxNDlhOGEzYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZN4oCb7nbwM3JMezxTPkP2MCeY8Vz8PyDCX6yokdP1A)
> 
> If this does not resolve your issue, please let me know which AWS region you are deploying to so we can try to replicate it on our side.
> 
> Thanks, Matt

Hi,
Thanks for the reply. The whole solution is not deployed in US, but EU - to be exact in the AWS region `eu-central-1`

**Comment by XsarfrazX** [comment]
It was indeed the geographic location restriction, which was set to USA even with the deployment region being eu-central-1. Once removed, the page loads properly. Thanks for your help

**Comment by mttwise** [comment]
No problem!  We will update our documentation with this information in the next release to help prevent this issue for others in the future.
